#!/usr/bin/node

var path = require('path'),
    fs = require('fs'),
    sys = require('sys'),
    exec = require('child_process').exec,
    utils = require('../utils');
    
var fileData = fs.readFileSync(
        path.join(__dirname, '../assets/config.js.template'), 'utf8');

exec('config-get --all --format=json', utils.substituteValues);
