#!/usr/bin/env node
var utils = require('../utils.js'),
    exec = require('child_process').exec;

function noop() {};

function getDBData(err, dbconfig) {
  var required_keys = ['user', 'database', 'password', 'private-address'];
  required_keys.map(function(key) {
    if(!(key in dbconfig)) {
      // We don't have the keys we need, exit silently by convention. 
      exec('juju-log DB Relation doesn\'t provide required keys.', noop);
      return;
    }    
  }); 
  
  // Merge db config keys into config.
  exec('config-get --all --format=json', function(error, config) {
    Object.keys(dbconfig).map(function(key) {
      config[key] = dbconfig[key]; 
    }); 
  });
  utils.substituteValues(null, config);
};

exec('relation-get --format=json', getDBData);
