#!/usr/bin/env node
var utils = require('../utils/utils'),
    dbutils = require('../utils/dbutils'),
    exec = require('child_process').exec;
// create the mysql switch so config-changed knows to leave db config alone.
exec('touch mysql');
exec('relation-get --format=json', dbutils.configureMysql);

/*
  Setup the mysql db config file.

  @method configureMysql
  @param {Object} err Exec function error
  @param {Object} config The json config data
*/
function configureMysql(err, config) {
  config = JSON.parse(config);
  var required_keys = ['user', 'database', 'password', 'private-address'];
  required_keys.map(function(key) {
    if(!(key in config)) {
      // We don't have the keys we need, exit silently by convention. 
      exec('juju-log DB Relation doesn\'t provide required keys.');
      return;
    }    
  }); 
  utils.renderTemplate(config, 'mysql.js.template', 'dbconfig.js');
};

exec('relation-get --format=json', configureMysql);
