#!/bin/bash

set -e

juju-log "Adding Node PPA."
add-apt-repository ppa:chris-lea/node.js -y

juju-log "Updating APT."
apt-get update

juju-log "Installing dependencies."
apt-get install nodejs rlwrap unzip

juju-log "Installing Ghost."
# Copy the upstart script to the proper location
cp -f assets/ghost.conf /etc/init/ghost.conf
chmod 644 /etc/init/ghost.conf
# Unzip and move to it's proper location
mkdir -p /var/www/ghost
unzip -uo assets/Ghost-0.4.1.zip -d /var/www/ghost

cd /var/www/ghost
npm install --production

touch /var/log/ghost.log
chown ubuntu:ubuntu /var/log/ghost.log

juju-log "Installation complete."
