#!/bin/bash

set -e

juju-log "Adding Node PPA."
wget -qO- https://deb.nodesource.com/gpgkey/nodesource.gpg.key | sudo apt-key add -

echo "deb https://deb.nodesource.com/node $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/nodesource.list
echo "deb-src https://deb.nodesource.com/node $(lsb_release -cs) main" | sudo tee -a /etc/apt/sources.list.d/nodesource.list

juju-log "Updating APT."
apt-get update

juju-log "Installing dependencies."
apt-get install nodejs rlwrap unzip

juju-log "Installing Ghost."
# Copy the upstart script to the proper location
cp -f assets/ghost.conf /etc/init/ghost.conf
chmod 644 /etc/init/ghost.conf
# Unzip and move to it's proper location
mkdir -p /var/www/ghost
LOCATION=$(config-get release_location)
juju-log "Fetching Ghost from location: ${LOCATION}"
wget -O /tmp/ghost.zip ${LOCATION}
unzip -uo /tmp/ghost.zip -d /var/www/ghost

cd /var/www/ghost
npm install --production

touch /var/log/ghost.log
chown ubuntu:ubuntu /var/log/ghost.log

juju-log "Installation complete."
